### ISSUE TITLE
Better organize content of SeLion-Grid.zip, once unzipped and running

### ISSUE THREAD

**Issue by mach6** [paypal/SeLion#11]
We need to clean up the directory in this area.
1. There are logs in the root folder and in the logs folder. Let's put them all in the same place.
2. Config files are mixed in with logs and binaries.. Let's put them in a separate folder
3. Downloaded content (from file downloader) also lands in the root folder. Should it too be in a separate folder?
4. Better organize windows and non-windows entities -- put things together in sub folders based on platform?

**Comment by ysecaran** [comment]
@mach6 : i am looking into this. Will update more on how to organize.
