### ISSUE TITLE
Unable to launch the app from HTTP URL path 

### ISSUE THREAD

**Issue by pearlselvan** [paypal/SeLion#111]
Unable to launch the app from HTTP URL path  .

Below is the SeLion code snapshot using appium as mobile node type 

public class SeLionConsumerApp {
    private static final String appFolder = "http://seliongrid:4444/grid/admin/TransferServlet/release/ios_demo.app.zip"; 
    @MobileTest(appPath = appFolder, device = "iphone:8.1", deviceType = "iPhone Simulator")
    @Test
    public void testNativeApp() throws InterruptedException {
    }
}

Error 

org.openqa.selenium.WebDriverException: org.openqa.selenium.SessionNotCreatedException: A new session could not be created. (Original error: Bad app: /Users/mselvansr/Documents/workspace/GridValidation/http:/10.244.244.132:4444/grid/admin/TransferServlet/consumervenice/consumervenice.app.zip. App paths need to be absolute, or relative to the appium server install dir, or a URL to compressed file, or a special app name. cause: Error: ENOENT, stat '/Users/mselvansr/Documents/workspace/GridValidation/http:/http://seliongrid:4444/grid/admin/TransferServlet/consumervenice/ios_demo.app.zip') (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 25 milliseconds

Required to add support for using HTTP URL path in SeLion's appPath Mobile Test Annotation

**Comment by squash-merge** [comment]
Fixed in commit id ec507e3823569ebf6c1b11879930b871cfe4a034

**Comment by mach6** [comment]
this is fixed
