### ISSUE TITLE
Enhance SeLion to start supporting  BrowserStack targetted runs

### ISSUE THREAD

**Issue by krmahadevan** [paypal/SeLion#127]
Request from one of the SeLion users,

SeLion currently doesn't support remote executions that are targeted against BrowserStack.

We would need to enhance SeLion to start providing support for BrowserStack as well.

For more details please refer to this forum thread

https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/selion/0ZR-OesRM1o/IVIXCLyUDggJ

**Comment by mach6** [comment]
This should already work. You set the `-DSELION_SELENIUM_HOSTNAME=username:automatekey@hub.browserstack.com` and the `-DSELION_SELENIUM_PORT={correct port}` .. Please re-open this ticket if that's not the case.

**Comment by krmahadevan** [comment]
@mach6 

BrowserStack seems to follow a different convention when it comes to forming the RemoteWebDriver URL
`public static final String URL = "http://" + USERNAME + ":" + AUTOMATE_KEY + "@hub.browserstack.com/wd/hub";`

SeLion on the other hand employs the below format to form the URL to construct a RemoteWebDriver URL [ See https://github.com/paypal/SeLion/blob/develop/client/src/main/java/com/paypal/selion/platform/grid/DriverFactory.java#L274 ] 

`url = new URL("http://" + hostToRun + ":" + port + "/wd/hub");`

Looks like BrowserStack doesn't have the concept of port but SeLion still expects a port number to provided for it form the URL. So in that case wouldn't we end up throwing a `java.net.MalformedURLException` ?

**Comment by mach6** [comment]
If you set the port to 80 it should work. It works when I run against Saucelabs in this fashion.

**Comment by mach6** [comment]
@krmahadevan  The URL RFC allows for `//<user>:<password>@<host>:<port>/<url-path>`, so I doubt the exception would be `java.net.MalformedURLException` --- http://tools.ietf.org/html/rfc1738

**Comment by SudhakaraPeram** [comment]
@mach6, @krmahadevan,
I have tried passing parameters as per @mach6 suggestion, it seems tests are routing to BrowserStack. Thanks for your help!

Now I need to set few extra capabilities (like OS Version, browserstack.debug, browserstack.local, etc) for all browsers, to do the same do I need to write my own class by extending DefaultCapabilitiesBuilder ? or is there anyway that I can pass them JVM args ?

Thanks in advance for your help!

**Comment by SudhakaraPeram** [comment]
@krmahadevan, @mach6,
Never mind, I was able to figure out how to pass custom capabilities using BeforeMethod annotation.

Thanks for your help!

**Comment by mach6** [comment]
@SudhakaraPeram interesting. There is an `additionalCapabilities` property for the `WebTest` annotation. I would have used that. I'm curious how you managed to do this in a `BeforeMethod`... Will you share the code snippet? 

Also, can we close this issue now?

**Comment by SudhakaraPeram** [comment]
@mach6 you can close this issue now.
I'm making use of ITestResult object (example shown in `ExtendedConfig`), here is my code snippet. 
I've not tested this code with sharing test session across test methods.

```
    @BeforeMethod
    public void setUpBStackCapabilities(ITestResult result) {
        DesiredCapabilities dc = new DesiredCapabilities();
        // Customize the capabilities
        dc.setCapability("os", "OS X");
        dc.setCapability("os_version", "Yosemite");
        dc.setCapability("browserstack.local", true);
        dc.setCapability("browserstack.debug", true);
        dc.setCapability("build", "<buildNum>");
        dc.setCapability("project", "projectName");
        // more capabilities
        result.setAttribute(ExtendedConfig.CAPABILITIES.getConfig(), dc);
    }
```

I need to enhance this to work for all types of platforms and browsers. 
I prefer above one if it works for tests that are sharing test session as I don't end up in writing `additionalCapabilities` property every time when I use `WebTest` annotation and less prone to making mistakes....

**Comment by mach6** [comment]
@SudhakaraPeram Ah yes! I forgot we had that option too! :)  Thanks.
