### ISSUE TITLE
Update documentation for 'customCapabilities' at http://paypal.github.io/SeLion/html/documentation.html#selion-config

### ISSUE THREAD

**Issue by SudhakaraPeram** [paypal/SeLion#128]
## Existing information at http://paypal.github.io/SeLion/html/documentation.html#selion-config

TestNG Suite file config value:   customCapabilities
JVM argument config value:  SELION_SELENIUM_CUSTOM_CAPABILITIES_PROVIDER:
Scope: GLOBAL
## Description: Use this parameter to provide SeLion with a custom listener which can be plugged into EventFiringWebDriver. If the fully qualified class implements WebDriverEventListener then SeLion will invoke the custom implementation provided by you via your implementation as and when the relevant events happen. If more than one custom listeners are to be provided please separate the fully qualified class names with commas.

Issue: Above description reads exactly same as "webDriverEventListener" config parameter.
I think it should read something as 
"Use this parameter to provide SeLion with a custom capabilities. The value for this parameter would be the fully qualified class name which is a sub-class of DefaultCapabilitiesBuilder. 
If more than one custom capabilities are to be provided please separate the fully qualified class names with commas."

**Comment by mach6** [comment]
Hi @SudhakaraPeram Thank you for the suggestion! Would you like to submit a pull request for the change? If so that would be awesome! If not, that's okay too. :)

**Comment by SudhakaraPeram** [comment]
Sure I'll do in a day. Thanks!

**Comment by SudhakaraPeram** [comment]
@mach6 Submitted pull request, can you please review. Thanks!
