### ISSUE TITLE
SeLion Grid does not get shutdown after run when using runLocally=true

### ISSUE THREAD

**Issue by renelux** [paypal/SeLion#129]
After the change with running locally the server is not getting shutdown correctly when the run is finished. When I run another grid is getting started which at some points leads to multiple running grid's which use up all system resources.

<img width="1373" alt="screen shot 2015-07-23 at 8 46 04 am" src="https://cloud.githubusercontent.com/assets/1439270/8854933/4f9d341e-3117-11e5-81f0-66288b0246c8.png">

**Comment by renelux** [comment]
This issue only occurs when there is another SeLion Grid is already started manually.

**Comment by mach6** [comment]
@renelux I don't follow. Are you first using SeLion-Grid-jar-with-dependencies to start a hub on the local machine and then ALSO running with runLocally=true on the SeLion "client" side? if so, then yes, I can see how this will create an issue -- it's not a scenario that we expect.

**Comment by renelux** [comment]
So the situation only occurs when there is another grid running on the machine. Problem is that the Grid gets started again (which does not work as port 4444 is already taken), but the process doesn't get killed and it ends up taking all CPU.

I know it is not an expected scenario, but can't you detect if there is a grid running and throw a error or a warning when that occurs? Or just connect to the Grid that someone already started.

**Comment by mach6** [comment]
@renelux will make a change to guard against port already in use.
