### ISSUE TITLE
Documentation - PayPal open source logo not diplayed on IE

### ISSUE THREAD

**Issue by mach6** [paypal/SeLion#14]
http://paypal.github.io/SeLion/  - The paypal open source svg is not displayed in newer IE versions..

**Comment by sundaramrajendran** [comment]
@mach6: I am working on this...

**Comment by mach6** [comment]
@sundaramrajendran  Code merged to gh-pages.. Thanks!

**Comment by mach6** [comment]
@sundaramrajendran FYI, Reopening this. It is not fixed for IE11

**Comment by sundaramrajendran** [comment]
@mach6 : I will fix this issue once I find a free time...

**Comment by mach6** [comment]
@sundaramrajendran Thanks! No rush. I'd rather have the new RuntimeReporter first. :)
