### ISSUE TITLE
Documentation - footer does not always stay on the bottom

### ISSUE THREAD

**Issue by mach6** [paypal/SeLion#15]
http://paypal.github.io/SeLion/html/documentation.html  

The footer on this section of the site does not always stay on the bottom as it should.

**Comment by sundaramrajendran** [comment]
@mach6 

Is this specific to any browser or any page for this issue. When I try to load the page footer is getting displayed and once content is loaded footer is moved to bottom of the page. Is this issue?

**Comment by mach6** [comment]
@sundaramrajendran the issue is on any browser, from what I see. The problem is the footer does not always align to the absolute bottom of the viewport/browser window -- like it does on the front page -- http://selion.io  ... to see the issue you need to have a viewport/browser with a large vertical area or load a page with a small amount of text.   The point you mention of the footer displaying and then moving directionally towards the bottom after the content is loaded is a secondary issue which can easily be fixed with some javascript which changes visibility from hidden to visible on document load.

**Comment by sundaramrajendran** [comment]
@mach6 I am working on this issue

**Comment by mach6** [comment]
PR merged to `gh-pages`
