### ISSUE TITLE
Update SeLion documentation and Sample iOS/android MobileTest Cases to Run On the Sauce Cloud

### ISSUE THREAD

**Issue by pearlselvan** [paypal/SeLion#191]
The following capabilities require to pass in SeLion annotation level to run the mobile test cases on the Sauce Cloud

"appiumVersion:1.4.3"

Currently its missing in Documentation page : http://paypal.github.io/SeLion/html/documentation.html#getting-started-mobile .

Sample iOS / android mobile test cases :
https://github.com/paypal/SeLion/blob/develop/client/src/test/java/com/paypal/selion/android/sample/AppiumAndroidBrowserSauceCloudTest.java
https://github.com/paypal/SeLion/blob/develop/client/src/test/java/com/paypal/selion/android/sample/AppiumAndroidNativeAppSauceCloudTest.java
https://github.com/paypal/SeLion/blob/develop/client/src/test/java/com/paypal/selion/ios/sample/AppiumIOSSafariSauceCloudTest.java

**Comment by mach6** [comment]
The archetype examples probably also need to be updated in this area -- https://github.com/paypal/SeLion/tree/develop/archetype/src/main/resources/archetype-resources/src/test/java/sample/selion

**Comment by mach6** [comment]
closed with commits
https://github.com/paypal/SeLion/commit/a2a68fd8e0be82eac469118a118edec7aeab7e01 https://github.com/paypal/SeLion/commit/2d2d20d6ba959d3030eeaec70317335d542dcf06
