### ISSUE TITLE
SeLion-Archetype buildtest fails with Maven 3.3.3 on Windows OS.

### ISSUE THREAD

**Issue by squash-merge** [paypal/SeLion#203]
Message is : [INFO]   Maven invocation failed. Error configuring command-line. Reason: Maven executable not found at: D:\installed\apache-maven\bin\mvn.bat

Root cause is the executable in Maven 3.3.3 is mvn.cmd whereas the one in Maven 3.2.3 is mvn.bat.

**Comment by squash-merge** [comment]
{ selion } develop » mvn -v                                                                       /d/workspace/sources/selion
Apache Maven 3.3.3 (7994120775791599e205a5524ec3e0dfe41d4a06; 2015-04-22T04:57:37-07:00)
Maven home: D:\installed\apache-maven
Java version: 1.7.0_45, vendor: Oracle Corporation
Java home: C:\java\jdk7\jre
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 7", version: "6.1", arch: "amd64", family: "windows"

**Comment by squash-merge** [comment]
References: https://issues.apache.org/jira/browse/MNG-5792

**Comment by mach6** [comment]
seems the fix is to move to a newer version of the invoker plugin.. we are on `1.8`. the latest is `2.0.0`

**Comment by mach6** [comment]
fixed with commit https://github.com/paypal/SeLion/commit/37ab3def18d6db26287c241689a4d4037ec574c6
