### ISSUE TITLE
Add gitter sidecar to documentation site.

### ISSUE THREAD

**Issue by mach6** [paypal/SeLion#204]
Perhaps we should add this widget in the footer of http://selion.io.. Of course we'll likely want to minimally customize the button

https://sidecar.gitter.im/

**Comment by ysecaran** [comment]
i just tried this. The style of the button by itself comes from the .js file specified
https://sidecar.gitter.im/dist/sidecar.v1.js
 What is the customization required for the button?

**Comment by ysecaran** [comment]
@mach6 I was able to get this added in footer at home page and the other pages too, but there seems to be slight delay in loading the page when clicking through the links on the right to view specific topics.
I will send out a pull request. Do let me know if it holds good.
