### ISSUE TITLE
Build instruction for SeLion is not clear

### ISSUE THREAD

**Issue by bingwei** [paypal/SeLion#21]
I tried following http://paypal.github.io/SeLion/html/documentation.html#buildingSelion to build SeLion.
But I was blocked for multiple times.
1. While building ios-driver for precondition, I need more clear information how to do it.
2. After getting ios-driver ready, blocked while running 
   mvn clean install -DSELION_SELENIUM_HOST=<location of your currently running selenium grid>
   I always got error info like this

```
Tests run: 0, Failures: 0, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] SeLion Parent POM ................................. SUCCESS [1.919s]
[INFO] SeLion Project BOM ................................ SUCCESS [0.036s]
[INFO] SeLion Client ..................................... FAILURE [30.085s]
[INFO] SeLion Grid ....................................... SKIPPED
[INFO] SeLion Code Generator Maven Mojo .................. SKIPPED
[INFO] SeLion Archetype .................................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 32.326s
[INFO] Finished at: Mon Sep 15 16:07:48 CST 2014
[INFO] Final Memory: 32M/368M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.17:test (default-test) on project SeLion: Execution default-test of goal org.apa
che.maven.plugins:maven-surefire-plugin:2.17:test failed: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was cmd.exe /X /C "C:\Java\jdk1.7.0_40\jre\bin\java -XX:MaxPermSize=128m -XX:-UseSplitVerifier -jar D:\workspace\SeLion\client\target\surefire\s
urefirebooter3754694759072562222.jar D:\workspace\SeLion\client\target\surefire\surefire2098405363173608294tmp D:\workspace\SeLion\client\target\surefire\surefi
re_07125297575698861365tmp"
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :SeLion
```

So last, I skip test and got it built finally.

I made a change in README about how did I build it on Windows platform.
Here's a link of my commit: https://github.com/bingwei/SeLion/commit/20170621b08fdaa4982c695472474c4e0c7ad1eb

I suggest to update SeLion build document on this part.

**Comment by mach6** [comment]
@bingwei  The error displayed is not really a SeLion related build error. It suggests that Maven surefire was unable to start. Do you have enough heap memory allocated to Maven? I use `MAVEN_OPTS=-Xmx1024m` when building SeLion

**Comment by mach6** [comment]
@bingwei thanks for the suggestions @ bingwei@2017062   In the latest `develop` branch, I have added a shell script for building ios-driver. This doesn't help much for people on Windows, but it should at least outline the steps required.  

Also, I noticed in your commit that you have added a localgrid. Are you aware of the `server` components included with SeLion? You should be able to compile this component, unzip/untar it and use it as a local grid for your needs. Note: If you are running the SeLion `client` tests against it and the `server` is not running on windows, you will have to pre-install `chromedriver`. 

All-in-all do the open tickets #9, #10, and #11 address all of your concerns in this area? 

Hope this helps!

**Comment by mach6** [comment]
@bingwei closing this. please re-open as you see fit.

**Comment by rakeshmick** [comment]
mvn clean test -DsuiteXmlFile=src/test/resources/SampleSuite.xml -DSELION_SELENIUM_RUN_LOCALLY=true

Try running with the -DSELION_SELENIUM_RUN_LOCALLY=true.
I got it running fine with this. Selion is looking for a remote grid, so you can just specify it to run locally.
