### ISSUE TITLE
SeLionSauceProxy should be more resilient to SauceLabs REST API failures

### ISSUE THREAD

**Issue by sebady** [paypal/SeLion#216]
SeLionSauceProxy should be more resilient against SauceLabs REST API failure. The proxy in getNewSession() method holds a lock when calling getNumberOfTCRunning().
    public TestSession getNewSession(Map<String, Object> requestedCapability) {
...
            accessLock.lock();
...
            if (getNumberOfTCRunning() <= maxTestCase) ...
...

Also GET method requests from getSauceLabsRestApi() using HttpURLConnection are not setting any timeout.

**Comment by mach6** [comment]
@sebady closing this due to the following commits. please re-open if more work remains.

https://github.com/paypal/SeLion/commit/c8a816c086612d3fd27450e969ec189a84b8a682
https://github.com/paypal/SeLion/commit/c9818dc264a38da56dcfcc4eb75a54e1ae3c4ec6
