### ISSUE TITLE
Updating SeLion documentation for JVM argument for SeLion Mobile App path

### ISSUE THREAD

**Issue by pearlselvan** [paypal/SeLion#219]
Required to update SeLion Document for app path which configurable in JVM argument 
http://paypal.github.io/SeLion/html/documentation.html#selion-config

Note : This information is available in http://paypal.github.io/SeLion/html/documentation.html#getting-started-mobile

**Comment by ysecaran** [comment]
The changes are done and there is an outstanding pull request.
