### ISSUE TITLE
SeLion is not considering DesiredCapabilities configured via TestNG Listener defined in plugin

### ISSUE THREAD

**Issue by sundaramrajendran** [paypal/SeLion#228]
Steps to reproduce the issue:

1) Create an Sample project which has TestNG listener IInvokedMethodListener implemnted to configure the DesiredCapabilities. Sample code

 @Override
 public void beforeInvocation(IInvokedMethod invokedMethod, ITestResult tr) {
   Proxy proxy = getProxy();
   DesiredCapabilities desiredCapabilities = new DesiredCapabilities();
   desiredCapabilities.setCapability(CapabilityType.PROXY, proxy);
   Capabilities caps = (Capabilities) tr.getAttribute(ExtendedConfig.CAPABILITIES.getConfig());
   if (caps != null) {
     desiredCapabilities.merge(caps );
   }
   tr.setAttribute(ExtendedConfig.CAPABILITIES.getConfig(), desiredCapabilities);  
 }

2) Configure above listener to the file META-INF/services/org.testng.ITestNGListener
3) Create an Test project with sample SeLion web test
4) Add SeLion as dependency to the Test project
5) Add Sample as dependency to the Test project
6) Run the web test in Test project

Actual Result:

Proxy is not configured to the browser.

Expected Result:

Proxy should be configured to the browser before executing test case in browser

Note: If we add Sample dependency as first and add SeLion depedency as second then we are getting expected results.

**Comment by mach6** [comment]
@sundaramrajendran personally, I don't see the need for injecting `ExtendedConfig.CAPABILITIES` into the TestNG attributes to accomplish the goal here. We have support for a custom capabilities provider - https://github.com/paypal/SeLion/blob/develop/client/src/main/java/com/paypal/selion/configuration/Config.java#L447-L453 and support for `additionalCapabilities` on the `@WebTest` and `@MobileTest` annotations. Unless you see a unique use case for injecting `ExtendedConfig.CAPABILITIES`, I think we should `@deprecate` the approach.

**Comment by sundaramrajendran** [comment]
We can add additional capabilities via SELENIUM_CUSTOM_CAPABILITIES_PROVIDER config, so this issue is not valid.
