### ISSUE TITLE
Printing debug info about browser taking ~75 sec or more on BrowserStack, need a way to turn it off

### ISSUE THREAD

**Issue by SudhakaraPeram** [paypal/SeLion#244]
DriverFactoryHelper.printDebugInfoForUser is taking ~75 sec or more on BrowserStack which is huge impact on automation suites in terms of time and this is obstacle for us to scale our automation.

DriverFactoryHelper.printDebugInfoForUser is being called from WebDriverFatory:
https://github.com/paypal/SeLion/blob/develop/client/src/main/java/com/paypal/selion/internal/platform/grid/browsercapabilities/WebDriverFactory.java#L87

Here is simple calculation on how time we are going to save (just for an example):
No. of tests \* 75 sec \* no. of browsers (i.e., 500 tests \* 75 sec = 37500 sec ~ 10 hrs per browser )

I think having a configurable option to turn it off (default = ON) would be useful for users who uses BrowserStack.

**Comment by mach6** [comment]
Note: @SudhakaraPeram asked to also contribute the change here. 😊

**Comment by mach6** [comment]
@SudhakaraPeram closing this issue since your changes are merged. Hopefully you are seeing an improvement in the latest 1.1.0-SNAPSHOT :)

**Comment by SudhakaraPeram** [comment]
@mach6 Yes, we are seeing an improvement in total execution time. Thanks!
