### ISSUE TITLE
documentation-broken link

### ISSUE THREAD

**Issue by alizelzele** [paypal/SeLion#257]
In documentation for [PageYAML for Android app automation](http://paypal.github.io/SeLion/html/documentation.html#android-native-page-yaml) `The list of supported Android elements` link is broken.

the list can be found in the [Source code](https://github.com/paypal/SeLion/tree/develop/client/src/main/java/com/paypal/selion/platform/mobile/android).

**Comment by mach6** [comment]
@alizelzele thanks for the heads up. The correct link should be http://paypal.github.io/SeLion/html/java-docs/1.0.0/client-apis/com/paypal/selion/platform/mobile/android/package-summary.html

If you would like to contribute the pull request for this, please let us know.

**Comment by mach6** [comment]
@alizelzele this is fixed.
