### ISSUE TITLE
Gradle Integration

### ISSUE THREAD

**Issue by knadendla** [paypal/SeLion#292]
Hi 

I have gradle project setup and i would like to integrate Selion features..  please let me know if there is sample integration is done...

**Comment by sebady** [comment]
Hi,

SeLion depends on testng as the suite/test runner. So build integration via gradle should be straight forward here for test executions using gradle java plugin with testng.  This assumes the test Project is not using SeLion code generator (which will require additional gradle customization here to use page yaml).

A sample build.gradle file like this (should work if project does not use page yaml) using 1.0.0 SeLion release:

apply plugin: 'java'
sourceCompatibility = "1.7"
repositories {
    mavenCentral()
}

dependencies {
    compile group: 'com.paypal.selion', name: 'SeLion', version: '1.0.0'
    compile group: 'com.paypal.selion', name: 'SeLion-Grid', version: '1.0.0'
    compile group: 'org.seleniumhq.selenium', name: 'selenium-server', version: '2.48.2'
}

test {
    useTestNG()
    // Path to testng suite file
    options.suites("src/test/resources/SampleSuite.xml")
}

**Comment by mach6** [comment]
@sebady thank you!
@knadendla Closing this for now. Please re-open if you have further questions or also feel free to ask them on our gitter.im channel
