### ISSUE TITLE
Move develop branch to SeLion 2.0.0 / Selenium 3

### ISSUE THREAD

**Issue by mach6** [paypal/SeLion#310]
The current develop branch should move to a `develop-1.2.0` branch to track fixes will we do to the Selenium 2.x compatible version of SeLion.

Afterwards;
- The `develop` branch needs to track SeLion 2.0.0 which will be forward-looking and Selenium 3.x compatible.
- New features should only be done on the `develop` branch with the only exception(s) being the new commit(s)  (marionette support) already merged to the pre-existing `develop` (copied to `develop-1.2.0`) branch since SeLion 1.1.0 was released.
- Bug fixes to `SeLion 1.x` should be done on the `develop-1.2.0`

**Comment by mach6** [comment]
@sebady fyi, selenium 3.0-beta2 is available on maven. We can setup the branches and start the work as planned.

**Comment by sebady** [comment]
Yippee! Do we have a change log of what's changing in selenium 3?

**Comment by mach6** [comment]
This is a start -- https://raw.githubusercontent.com/SeleniumHQ/selenium/master/java/CHANGELOG

**Comment by mach6** [comment]
There will be quite a few compilation things to address in the SeLion `server` component, for starters. Places, where we will have to move to the new path. Also, these `server` changes likely are not going to be compatible with our ios-driver and selendriod support in the `server` component -- at least until those projects also move ahead to selenium 3.x

**Comment by mach6** [comment]
the branch `develop` is now is based on Se3 (beta3)
