### ISSUE TITLE
Add configuration setting to set selion log file limits.

### ISSUE THREAD

**Issue by mach6** [paypal/SeLion#32]
With the recent changes to `SimpleLogger` (which is used by `SeLionLogger`) https://github.com/paypal/SeLion/commit/003b48052acddf8e7c3ba7f7499cbe893eda8b46 we have an opportunity to add a new configuration option that will control the log file limits. For example, we can now limit the number of log files and/or the size before rolling to a new file. We should define a default behavior, add it to our `SeLionLoggerSettings`, and give the user the ability to override the default behavior.

**Comment by ysecaran** [comment]
@mach6 : I am getting this done. Will send out a pull request after testing

**Comment by mach6** [comment]
This was fixed with #151
