### ISSUE TITLE
Update geckodriver for SeLion 1.2?

### ISSUE THREAD

**Issue by sebady** [paypal/SeLion#337]
### SeLion Version

Selion 1.2

SeLion 1.x should use latest available geckodriver version supported by Selenium 2.53

**Comment by sebady** [comment]
Unfortunately without this selenium fix: 
https://github.com/SeleniumHQ/selenium/pull/2255

The selenium 2.53.x geckodriver support is not very usable currently.

**Comment by mach6** [comment]
@sebady Good to close this issue?
