### ISSUE TITLE
Providing Feedback to the user when the node is currently under restart or auto -upgrade

### ISSUE THREAD

**Issue by ysecaran** [paypal/SeLion#34]
There is no feedback mechanism when the node is force restarted. 
The UI immediately says auto restart successful when it is happening in the background.
The users must be notified about this. This is same when the auto upgrade is triggered.

**Comment by mach6** [comment]
Commit https://github.com/paypal/SeLion/commit/cd3f5bd54cd326cd123a8e41638a09a0a685d33d added feedback when a node is scheduled for a restart.

**Comment by mach6** [comment]
@ysecaran closing this per my previous comment. 1.0.0 included provisions for this.
