### ISSUE TITLE
Does selion have a soulation about how to deal with AJAX request in my page

### ISSUE THREAD

**Issue by DaleAuto** [paypal/SeLion#348]

**Comment by mach6** [comment]
Please ask questions like this via our gitter channel. 

That said, this is more of a selenium question. 

The recommended approach (and one that SeLion's page object's and elements embrace) is to interact with the page in a fashion where you look for an expectation to occur before the Selenium timeout.

In SeLion, this comes to light with `AbstractElement#click(Object ... expected)` -- [javadocs](http://paypal.github.io/SeLion/html/java-docs/1.2.0/client-apis/com/paypal/selion/platform/html/AbstractElement.html)  and/or  PageYaml `pageValidators` -- [docs](http://paypal.github.io/SeLion/html/documentation.html#pageyaml)  

Both of these methods have proven to be effective..
