### ISSUE TITLE
Query: Parallel & Distributed execution

### ISSUE THREAD

**Issue by vikramvi** [paypal/SeLion#363]
Hi,

This is generic query, so couldn't add other details per issue template

1. Does the framework supports test cases distribution with Selenium Grid scenario ? 
   This is to achieve quick regression, assign test cases to available nodes and finish automation quickly

2. Does the framework supports parallel execution with Selenium Grid scenario ? 
   This is to achieve compatibility testing, to test same set of test cases on various browsers on same time.

Thanks in advance.

Regards,
Vikram

**Comment by sebady** [comment]
With SeLion the concurrency of executions is achieved via TestNG's support for parallelism.  See this page for more details http://testng.org/doc/documentation-main.html#parallel-running

The SeLion grid supports scaling out several browsers across grid nodes.  With the right configuration of browsers you can perform concurrent validation across all browsers supported by the Selion grid.

**Comment by vikramvi** [comment]
@sebady by **concurrency** do you mean distribution of test cases  or running same test cases on all the nodes ? 

- Does this framework has any setting to ask for parallel or distributed run ?

Thanks again.

**Comment by sebady** [comment]
Only the web browsers are distributed across nodes via the Selenium/SeLion grid.  The test classes themselves are limited to the parallelism offered by TestNG.  I.e. parallel runs executing on a single client.  Usually you can setup a jenkins slave farm if you really need to distribute a large suite's execution further across several jenkins slaves.   SeLion leaves scaling of the test class (I.e SeLion client) to other technologies that are better suited for this and based on the specific use cases required.

**Comment by sebady** [comment]
I'm closing this issue. Please reach out to us on gitter (https://gitter.im/paypal/SeLion) if you have further questions.

**Comment by vikramvi** [comment]
@sebady thanks for additional info. Sure will join gitter in case of further clarifications
