### ISSUE TITLE
Using Grid.driver() we are not able to get FindElementAccessbilityId Issue,please check 

### ISSUE THREAD

**Issue by mahe12** [paypal/SeLion#377]

**Comment by mach6** [comment]
Please provide more detail. SeLion version? Selenium version?  

Also, what makes you think `FindElementAccessbilityId` is missing?

`Grid.driver()` returns a `RemoteWebDriver` object -- which has no such method. See the javadocs -- https://seleniumhq.github.io/selenium/docs/api/java/org/openqa/selenium/remote/RemoteWebDriver.html

**Comment by mach6** [comment]
@mahe12 closing due to no response.
