### ISSUE TITLE
Selion Dependency Issue

### ISSUE THREAD

**Issue by BoomaRajan** [paypal/SeLion#386]
### SeLion Version
1.2.0
### Component
SeLion
### Expected Behavior
When I added dependency of SeLion.My Actual test script should work
### Actual Behavior
When I added dependency of SeLion.My test script are ignored 
ClassNotFoundException com.paypal.selion.logger.SeLionLogger

My java project has already testng and selenium dependency

Steps to Reproduce

Add  testng and selenium driver dependency.
Build script using selenium API.
Add the seLion dependency.
Run the test script ,It will throw an error

**Comment by mach6** [comment]
`SeLionLogger` is part of the SeLion-Common.jar artifact. Make sure you add that as a dependency also, if your dependency management system is failing to pull it in automatically for you.

See - http://paypal.github.io/SeLion/html/java-docs/1.2.0/common-apis/index.html

Also, it sometimes helps in instances like this if you can include an example.
