### ISSUE TITLE
issues with documentation 

### ISSUE THREAD

**Issue by sankarbhavanib** [paypal/SeLion#41]
started with getting-started for web project . came across below documentation issues 

http://paypal.github.io/SeLion/html/documentation.html#getting-started
- [x] 1   The steps says the sample project will get  created in the below path "src/main/com/mycompany/test" , but it actually created sample project in below path "src/main/java/com/mycompany/test" 
- [x] 2   the steps says to go to folder {project}/src/test/resources and crate suite file . but there is no "resources" folder in that path , it need to be created , may be we need to add step "mkdir resources" before move to suite file creation step 
- [x] 3 after creating the suite file the prompt location will be "{project}/src/test/resources" . if we try to run "mvn clean test -DsuiteXmlFile=src/test/resources/SampleSuite.xml" it will not work . for that command to work we need to move to "{project}/" folder before we run that

**Comment by mach6** [comment]
:+1: fixed thanks!
