### ISSUE TITLE
Code refactoring opportunities

### ISSUE THREAD

**Issue by mach6** [paypal/SeLion#48]
- Left unaddressed from #44
- [ ] In `com.paypal.selion.platform.grid.LocalSelendroidNode` the following methods are being duplicated from `com.paypal.selion.platform.grid.LocalIOSNode`. Can we consider creating an `AbstractNode` from which both `LocalSelendroidNode` and `LocalIOSNode` extend and house these two methods in the abstract class ?
  `com.paypal.selion.platform.grid.LocalSelendroidNode.waitForNodeToComeUp(int)`
  `com.paypal.selion.platform.grid.LocalSelendroidNode.wasNodeSpawned(int)`
- [ ] In `com.paypal.selion.platform.grid.LocalSelendroidNode.startSelendroidDriverNode(int)` can we consider using `org.apache.commons.io.filefilter.FileFilterUtils` ?

**Comment by mgooty** [comment]
@mach6 - I would like to pick up this code re-factoring task. Before that I wanted to  know if someone is working on this issue? If no one is working, please assign the issue to me.

**Comment by krmahadevan** [comment]
@mgooty 
Mithun,
To the best of my knowledge no one is working on this. So if you would like to take a go at this, please feel free to do it. But please do mention in the comments that you would be working on it.

**Comment by mgooty** [comment]
@krmahadevan - Thank you for the confirmation. I will be working on this issue.

**Comment by krmahadevan** [comment]
The Pull request https://github.com/paypal/SeLion/pull/51 addresses this issue.
