### ISSUE TITLE
SeLion-Grid: Download platform specific drivers on OSX and Linux

### ISSUE THREAD

**Issue by renelux** [paypal/SeLion#50]
When running the SeLion Grid on Mac it will download all the Windows drivers. Instead it should download the drivers specific to the platform that we are running on.

**Comment by ysecaran** [comment]
Rene, This is already taken care as part of the following issue: https://github.com/paypal/SeLion/issues/10 . There is an outstanding pull request.

**Comment by renelux** [comment]
Sorry, I missed that one. I will close this issue.
