### ISSUE TITLE
Selion documentaion issue in maven-surefire-plugin version

### ISSUE THREAD

**Issue by pearlselvan** [paypal/SeLion#65]
Started with getting-started for mobile automation in below link . came across below documentation issues

http://paypal.github.io/SeLion/html/documentation.html#getting-started-mobile

Found out that maven-surefire-plugin : 2.12 version which is updated the above Selion link is having the issue to run the script .

Got error "Error occurred in starting fork” when I am running the script with maven-surefire-plugin : 2.12 due to the bug in (https://jira.codehaus.org/browse/SUREFIRE-870) In maven-surefire-plugin .

After I changed the version to 2.17 , I am not getting that error .

**Comment by pearlselvan** [comment]
Fixed this issue and raised the pull request #68

**Comment by krmahadevan** [comment]
@pearlselvan 

Issues should be closed only after the pull request has been merged.

**Comment by pearlselvan** [comment]
@krmahadevan , Thanks Krishnan , I will do that .

**Comment by mach6** [comment]
this is addressed and merged
