### ISSUE TITLE
Unclear documentation w.r.t naming locators/selectors in PageYAML

### ISSUE THREAD

**Issue by mach6** [paypal/SeLion#72]
The page http://paypal.github.io/SeLion/html/documentation.html#pageyaml incorrectly conveys that each SeLion Element type strictly maps to a html element. We need to fix this.

Problematic text

```
The name to be given to identifying the locator/selector. This name would end up serving as the data member in the generated class and maps to the html element specified. The rules for naming locators/selectors are as follows:
<prefix>Button Is a Button html element.
<prefix>CheckBox Is a Check Box html element.
<prefix>DatePicker Is a Date Picker html element.
<prefix>Form Is a Form html element.
<prefix>Image Is a Image html element.
<prefix>Label Is a Label html element.
<prefix>Link Is a Link html element.
<prefix>RadioButton Is a Radio Button html element.
<prefix>List Is a Select List html element.
<prefix>Table Is a Table html element.
<prefix>TextField Is a Text Field html element.
<prefix>Container Is a Container html element.
```

More accurately, the following is true;

If you look at the code for all of the Element types unique to SeLion, none of them are strictly tied to a html element. 

Rather, they each expose a set of properties or methods which one would expect to map to the html element that gives the class it's name. So, in the case of `Label`, the class only adds the method `isTextPresent()`. This means you can expect that if you pass any locator to an html element with inner text, you can map it to `Label` in PageYAML and access the `isTextPresent()` method in java code. You can use `Label` for a `div`, `span`, `p` nodes, for example, if you are looking to verify the text contained by them.

**Comment by ysecaran** [comment]
I am looking into this
