### ISSUE TITLE
Getting started documentation

### ISSUE THREAD

**Issue by rakeshmick** [paypal/SeLion#76]
I was  going through the getting started document of Selion.
http://paypal.github.io/SeLion/html/documentation.html#getting-started

In that,  the mvn command to run the test suite is  given as
just mvn clean test -DsuiteXmlFile=src/test/resources/SampleSuite.xml,
but that  did not help me and it was throwing some error.
I had to add -DSELION_SELENIUM_RUN_LOCALLY=true, It would be great if you can update the  document with that .

mvn clean test -DsuiteXmlFile=src/test/resources/SampleSuite.xml -DSELION_SELENIUM_RUN_LOCALLY=true.

I can find it described at different parts in the documentation, but not in getting started.

**Comment by mach6** [comment]
The line `<parameter name="runLocally" value="true"/>` in the `SampleSuite.xml` shown on the getting-started page accomplishes the same thing. The only difference is hard-coded configuration (in the suite file) vs. configuration specified at runtime (as JVM system property)

perhaps you missed this line?
