### ISSUE TITLE
Code-Generator: Add support for custom elements

### ISSUE THREAD

**Issue by renelux** [paypal/SeLion#81]
We would like to add support for custom elements in the CodeGenerator. We would like to handle webpages that are build with ExtJS and if you look at for [example](http://dev.sencha.com/deploy/ext-4.0.0/examples/form/fieldcontainer.html) their drop down list. You will see that the default implementation is not going to work.

For us to be able to use our best practices for web automation we would like to have custom element in the CodeGenerator that can handle this kind of non default behavior.
# Proposed implementation:

Add a property to the Code-Generator which accepts a comma separated list of java classes. Based on the parameters we can add the imports and create getters and setters in the generated Pages. Example "com.rlux.test.elements.ExtJSSelectList,com.rlux.test.elements.ExtJSTable"

Output:

```
import com.rlux.test.elements.ExtJSSelectList;

private ExtJSSelectList categoryExtJSSelectList;

public ExtJSSelectList getCategoryExtJSSelectList() {
    return categoryExtJSSelectList;
}

public void setCategoryExtJSSelectList(ExtJSSelectList categoryExtJSSelectList) {
    this.categoryExtJSSelectList = categoryExtJSSelectList;
}
```

Any concerns for such functionality, and any feedback what to focus on if we would want to implement it?

**Comment by mach6** [comment]
Closing this issue. #91 is tracking the outstanding documentation need for this enhancement
