### ISSUE TITLE
Code-Generator produces code which will not compile when PageYaml document resides in src/main/resources/GUIData

### ISSUE THREAD

**Issue by mach6** [paypal/SeLion#84]
- [x] If you put a PageYaml document in the top-level folder under src/main/resources/GUIData, the code-generator will produce a corresponding class with and invalid `package` declaration -- it will end with a `.`
- [x] Also, the site documentation http://paypal.github.io/SeLion/html/documentation.html#what-is-code-generator, bullet 2 under "Put the SeLion Code Generator in Action" is mis-leading. The file, once created, should reside in ANY directory under src/main/resources/GUIData ... It does not have to be placed in the top-level of this location.

**Comment by ysecaran** [comment]
@mach6 I am looking into this

**Comment by mach6** [comment]
fix is merged
